
kind: pipeline
name: docker
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: compose
    image: linuxserver/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose down && docker-compose up -d
      - docker system prune -f
  

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock