kind: pipeline
name: iot-web
type: docker


platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:16.5.1-stretch-slim
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: build
        path: /drone/src/dist
    commands:
      - npm install -g yarn
      - "yarn && npm run build"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: node_modules
    host:
      path: /root/node/node_modules/iot-web
  - name: build
    host:
      path: /root/wwwroot/iot-web