kind: pipeline
name: iot-web
type: docker


platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:16.5.0-stretch-slim
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: dist
        path: /drone/src/dist
    commands:
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - "npm i && npm run build"
      - $PWD

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: node_modules
    host:
      path: /root/node/node_modules/iot-web
  - name: dist
    host:
      path: /root/wwwroot/iot-web