version: '3.7'
services:
  node:
    image: node:16.5.0-stretch-slim
    container_name: node
    restart: always
    volumes:
      - /root/wwwroot/iot-web:/drone/src/dist
      - /root/node/node_modules:/drone/src/node_modules
    build: 
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - "npm i && npm run build"
    
    networks:
      - token

networks:
  token:
    external: true