version: '3.7'
services:
  iot-auth:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/iot-auth:dev
    container_name: iot-auth
    restart: always
    volumes:
      - /root/wwwroot/iot-web:/drone/src/dist
    command: 
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - "npm i && npm run build"
    networks:
      - token
